config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'main#index'

  get 'admin', :to => 'admin#menu'

  get 'admin/login'

  post 'admin/attempt_login'

  get 'logout', :to => 'admin#logout'

  resources :customers, only: [:create] do
  end

  resources :events, only: [:show, :create, :update, :destroy], :path => 'registered', param: :title  do
  end

  resources :future_events, only: [:create, :update, :destroy] do
  end

  get 'main/index'

  get 'formacion', :to => 'main#formacion'

  get 'evangelizacion', :to => 'main#evangelizacion'

  get 'rccho', :to => 'main#rccho'

  get 'selected_event', :to => 'main#find_event'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password

  validates_presence_of :username
  validates_uniqueness_of :username

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord

  belongs_to :event

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :telephone
  validates_presence_of :address1
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip
  validates_presence_of :first_name2
  validates_presence_of :last_name2
  validates_presence_of :relationship
  validates_presence_of :telephone2
  validates_presence_of :event_id

end

app/models/event.rb
class Event < ApplicationRecord

  def to_param
   title
  end

  has_many :customers, lambda { reorder(first_name: :asc) }

  validates_presence_of :title
  validates_presence_of :description
  validates_length_of :date, :is => 8
  validates_presence_of :price


end

app/models/future_event.rb
class FutureEvent < ApplicationRecord

  validates_presence_of :title
  validates_length_of :date, :is => 8

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout 'application'

  before_action :confirm_logged_in, :except => [:attempt_login, :logout]

  def menu
    @counter = Event.last
    @events = Event.all
    @events.each do |event|
      if event.customers.size == event.capacity
        event.update_attributes(:visible => false)
      end
    end
    @future_events = FutureEvent.all
    @customers = Customer.all
  end

  def attempt_login

    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "Logged in"
      render js: "window.location = '#{admin_path}'"
    else
      flash[:notice] = "Invalid username or password"
      render js: "window.location = '#{root_path}'"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to(root_path)
  end

  private

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(root_path)
    end
  end

end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApplicationController
      respond_to :json

      def index
        render :json => Event.all
      end

      def show
        render :json => Event.find(params[:id])
      end

      def create
        render :json => Event.create(params[:event])
      end

      def update
        render :json => Event.update(params[:id], params[:event])
      end

      def destroy
        render :json => Event.destroy(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def create
    @customer = Customer.new(customer_params)
    eventid = @customer.event_id
    event = Event.find(eventid)
    price = event.price
    fprice = price.to_i
    if @customer.save && price == 0
      flash[:notice] = "Free registered"
      flash[:title] = event.title
      flash[:name] = @customer.first_name + " " + @customer.last_name
      flash[:email] = @customer.email
      flash[:price] = fprice
      flash[:date] = event.date
      redirect_to(root_path)
    elsif @customer.save
      charge = price.gsub(/[.]/, '')
      charge = charge.to_i
      Stripe.api_key = "sk_test_Uqgr2je9Z41t0un6gLuCB7bQ"
      token = params[:stripeToken]
      charge = Stripe::Charge.create(
        :amount => charge,
        :currency => "usd",
        :description => event.title + ": " + @customer.first_name + " " + @customer.last_name,
        :statement_descriptor => event.title,
        :source => token,
        :receipt_email => @customer.email,
      )
      flash[:notice] = "Registered"
      flash[:title] = event.title
      flash[:name] = @customer.first_name + " " + @customer.last_name
      flash[:email] = @customer.email
      flash[:price] = fprice
      flash[:date] = event.date
      redirect_to(root_path)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :telephone, :address1, :email, :city, :state, :zip, :church, :gender, :first_name2, :last_name2, :relationship, :telephone2, :event_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :confirm_logged_in, :except => [:create, :update, :destroy]

  def show
    @event = Event.find_by(title: params[:title])
    respond_to do |format|
      format.pdf do
          pdf = RegisteredPdf.new(@event)
          send_data pdf.render, filename: "Registered: #{@event.title}",
                                type: "application/pdf",
                                disposition: "inline"
      end
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Successfully made new event: #{@event.title}"
      redirect_to(admin_path)
    end
  end

  def update
    @event = Event.find_by(title: params[:title])
    if @event.update_attributes(event_params)
      flash[:notice] = "Successfully updated #{@event.title}"
      redirect_to(admin_path)
    end
  end

  def destroy
    @event = Event.find_by(title: params[:title])
    @event.customers.destroy
    @event.destroy
    flash[:notice] = "Successfully deleted #{@event.title}"
    redirect_to(admin_path)
  end

  private

  def confirm_logged_in
    unless session[:user_id]
      redirect_to(root_path)
    end
  end

  def event_params
    params.require(:event).permit(:title, :date, :description, :price, :capacity, :visible)
  end

end

app/controllers/future_events_controller.rb
class FutureEventsController < ApplicationController

  layout 'application'

  def create
    @fevent = FutureEvent.new(event_params)
    if @fevent.save
      flash[:notice] = "Successfully made new future event: #{@fevent.title}"
      redirect_to(admin_path)
    end
  end

  def update
    @fevent = FutureEvent.find(params[:id])
    if @fevent.update_attributes(event_params)
      flash[:notice] = "Successfully updated #{@fevent.title}"
      redirect_to(admin_path)
    end
  end

  def destroy
    @fevent = FutureEvent.find(params[:id])
    @fevent.destroy
    flash[:notice] = "Successfully deleted #{@fevent.title}"
    redirect_to(admin_path)
  end

  private

  def event_params
    params.require(:future_event).permit(:title, :date, :kind)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @events = Event.all
    @events.each do |event|
      if event.customers.size == event.capacity
        event.update_attributes(:visible => false)
      end
    end
    @future_events = FutureEvent.all
    @customer = Customer.all
  end

  def find_event
    found_event = Event.find(params[:format])
    flash[:notice] = "selected event found"
    flash[:ftitle] = found_event.title
    flash[:id] = found_event.id
    flash[:fprice] = found_event.price
    p flash[:fprice]
    render js: "window.location = '#{root_path}'"
  end

  def formacion
  end

  def evangelizacion
  end

  def rccho
  end

  def checkout
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/future_events_helper.rb
module FutureEventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/_eventForm.html.erb
<strong><span class="hint">&#42;</span>Nombre </strong><br />
<%= f.text_field(:title, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Fecha </strong><br />
<%= f.text_field(:date, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Precio </strong><br />
<%= f.text_field(:price, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Description </strong><br />
<%= f.text_area(:description, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Capacidad </strong><br />
<%= f.text_field(:capacity, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Status </strong><br />
<div class="row">
  <div class="col-3"></div>
  <div class="col-3"><%= f.radio_button(:visible, true, :checked => true, :class => 'form-control') %>Open</div>
  <div class="col-3"><%= f.radio_button(:visible, false, :class => 'form-control') %>Closed</div>
  <div class="col-3"></div>
</div><br />
<div class="container text-left">
  <span class="hint">&#42;Required</span>
</div><br />

app/views/admin/_feventForm.html.erb
<strong><span class="hint">&#42;</span>Nombre </strong><br />
<%= f.text_field(:title, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Fecha </strong><br />
<%= f.text_field(:date, :class => 'form-control') %><br />
<strong><span class="hint">&#42;</span>Typo </strong><br />
<%= f.text_field(:kind, :class => 'form-control') %><br />
<div class="container text-left">
  <span class="hint">&#42;Required</span>
</div><br />

app/views/admin/menu.html.erb
<article>
	<div class="container">
    <header class="row adminl text-right">
			<div class="col">
				<%= link_to 'Principal', root_path, :class => 'adminlink' %>
			</div>
    </header>
		<header class="row adminl text-right">
			<div class="col">
				<%= link_to 'Logout', logout_path, :class => 'adminlink' %>
			</div>
    </header>
  </div>
  <div class="container text-center">
    <header class="row">
      <h1 class="col">Renovacion Catolica Caristmatica</h1>
    </header>
  </div>
	<% if !flash[:notice].blank? %>
		<div class="alert alert-dismissible fade show" role="alert">
		<strong><%= flash[:notice] %>!</strong>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		</div>
	<% end  %>
	<div class="container-fluid text-center title">
		<div class="row">
		  <h2 class="col">Administrative menu</h2>
	  </div>
	</div>
	<div class="container text-center">
		<h2>Eventos</h2>
	</div>
	<div class="container text-center">
		<div class="row">
	  <% @events.each do |event| %>
			<section class="col-12 col-sm-3">
				<h3><%= event.title %></h3>
				<p class="text-justify text-center">
				<em>Fecha</em>: <%= event.date %>
				<br />
				<br />
				<em>Description</em>: <%= event.description %><br /><br />
        <em>Precio</em>: <%= number_to_currency(event.price) %><br /><br />
				<% sl = event.capacity - event.customers.size %>
				<button class="badge-btn">
					<em>Capacidad</em> <span class="badge badge-light"><%= event.capacity %></span>
				</button><br /><br />
				<% if sl > 0 %>
					<button class="badge-btn">
						<em>Espacio disponibles</em> <span class="badge badge-light"><%= sl %></span>
					</button><br /><br />
				<% else %>
					<button class="badge-btn">
						<em>Espacio disponibles</em> <span class="badge badge-light">0</span>
					</button><br /><br />
				<% end %>
				<% if event.visible %>
				  <em>Status</em>: Open<br /></p>
				<% else %>
					<em>Status</em>: Closed<br /></p>
				<% end %>
				<div class="row">
					<!-- Edit event Modal button <%= event.id %> -->
					<div class="col-12">
						<button type="button" title="Edit" class="button" data-toggle="modal" data-target="#EditModal-<%= event.id %>">
						  Edit
						</button>
					</div>
					<!-- Delete event Modal button <%= event.id %> -->
					<div class="col-12">
						<button type="button" title="Delete" class="button" data-toggle="modal" data-target="#DeleteModal-<%= event.id %>">
						  Delete
						</button>
					</div>
					<!-- Registered customers Modal button <%= event.id %> -->
					<div class="col-12">
						<button type="button" title="Delete" class="button" data-toggle="modal" data-target="#RegisteredModal-<%= event.id %>">
						  Registered
						</button>
					</div>
				</div>
				<br />
				<!-- Edit event Modal <%= event.id %> -->
				<div class="modal fade" id="EditModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Edit event</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
							<div class="container text-center">
						    <div class="row form-group">
						      <div class="col"></div>
						      <div class="col-8"><br />
                    <%= form_for event, :method => 'patch' do |f| %>
						          <%= render(:partial => 'eventForm', locals: {:f => f}) %>
						          <%= f.submit "Update event", :class => 'button submit' %>
						        <% end %>
						      </div>
						      <div class="col"></div>
						    </div>
						  </div>
				      <div class="modal-footer">
								<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
				      </div>
				    </div>
				  </div>
				</div>
				<!-- Delete event Modal <%= event.id %> -->
				<div class="modal fade" id="DeleteModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Delete event</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
							<div class="addmargin">
								<p>Are you sure you wanna permanetly delete this event?</p><br />
								<p>Name: <%= event.title %></p><br />
								<p>Date: <%= event.date %></p><br />
							</div>
				      <div class="modal-footer">
								<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
								<%= link_to 'Delete', event_path(event), :method => 'delete', :class => 'button' %>
				      </div>
				    </div>
				  </div>
				</div>
				<!-- Registered customers Modal <%= event.id %> -->
				<div class="modal fade" id="RegisteredModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Registered for: <%= event.title %></h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
							<% if event.customers.any? %>
								<div class="container">
									<div class="table-responsive">
										<table class="table">
											<thead>
												<tr>
													<th scope="col">#</th>
													<th scope="col">Name</th>
													<th scope="col">Gender</th>
												</tr>
											</thead>
											<tbody>
												<% i = 0 %>
												<% event.customers.each do |p| %>
												<% i += 1 %>
												<tr>
													<td><%= i %></td>
													<td><%= p.first_name %> <%= p.last_name %></td>
													<td><%= p.gender %></td>
												</tr>
												<% end %>
											</tbody>
										</table>
									</div>
									<div class="row">
										<div class="col-12">
											<%= link_to 'Registered', event_path(event, :format => 'pdf'), :target => "_blank",:class => 'button submit' %><br /><br />
										</div>
									</div>
								</div>
							<% else %>
								<div class="text-center">
									<h2>No registered people</h2>
								</div>
							<% end %>
				      <div class="modal-footer">
								<%= link_to 'Close', admin_path, :'data-dismiss' => "modal", :class => 'button submit' %>
				      </div>
				    </div>
				  </div>
				</div>
	    </section>
		<% end %>
	  </div>
		<% unless @counter %>
		<% else %>
			<div class="row">
				<div class="col-12">
					<p># of events: <%= @counter.id  %></p>
				</div>
			</div>
		<% end %>
    <div class="row">
			<!-- Add event Modal button -->
			<div class="col-12">
				<button type="button" title="Add new event" data-backdrop="static" class="button" data-toggle="modal" data-target="#AddModal">
					Add new event
				</button>
			</div>
		</div>
		<!-- Add event Modal -->
		<div class="modal fade" id="AddModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Add new event</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="container text-center">
				    <div class="row form-group">
				      <div class="col"></div>
				      <div class="col-8"><br />
				        <%= form_for @events.new, :method => 'post' do |f| %>
									<%= render(:partial => 'eventForm', locals: {:f => f}) %>
				          <%= f.submit "Add new event", :class => 'button submit' %>
				        <% end %>
				      </div>
				      <div class="col"></div>
				    </div>
				  </div>
					<div class="modal-footer">
						<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
					</div>
				</div>
			</div>
		</div>
    <div class="text-center">
			<h2>Futuro eventos</h2>
		</div>
		<div class="table-responsive">
			<table class="table">
				<caption class="text-center">Futuro eventos</caption>
			  <thead>
			    <tr>
			      <th>Fecha</th>
			      <th>Evento</th>
						<th>Typo</th>
            <th colspan="2">Actions</th>
			    </tr>
			  </thead>
				<% @future_events.each do |event| %>
			  <tbody>
			    <tr class="thover">
			      <th><%= event.date %></th>
			      <td><%= event.title %></td>
						<td><%= event.kind %></td>
            <td>
							<div class="row">
								<!-- Edit future event Modal link <%= event.id %> -->
                <div class="col">
                  <a href="#EditfModal-<%= event.id %>" data-toggle="modal" >Edit</a>
									<!-- Edit future event Modal <%= event.id %> -->
									<div class="modal fade" id="EditfModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
										<div class="modal-dialog" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<h5 class="modal-title" id="exampleModalLabel">Edit future event</h5>
													<button type="button" class="close" data-dismiss="modal" aria-label="Close">
														<span aria-hidden="true">&times;</span>
													</button>
												</div>
												<div class="container text-center">
													<div class="row form-group">
														<div class="col"></div>
														<div class="col-8"><br />
															<%= form_for event, :method => 'patch' do |f| %>
																<%= render(:partial => 'feventForm', locals: {:f => f}) %>
																<%= f.submit "Update future event", :class => 'button submit' %>
															<% end %>
														</div>
														<div class="col"></div>
													</div>
												</div>
												<div class="modal-footer">
													<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
												</div>
											</div>
										</div>
									</div>
                </div>
								<div class="col">
                  <a href="#DeletefModal-<%= event.id %>" data-toggle="modal" >Delete</a>
									<!-- Delete future event Modal <%= event.id %> -->
									<div class="modal fade" id="DeletefModal-<%= event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
										<div class="modal-dialog" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<h5 class="modal-title" id="exampleModalLabel">Delete future event</h5>
													<button type="button" class="close" data-dismiss="modal" aria-label="Close">
														<span aria-hidden="true">&times;</span>
													</button>
												</div>
												<div class="addmargin">
													<p>Are you sure you wanna permanetly delete this future event?</p><br />
													<p>Name: <%= event.title %></p><br />
													<p>Date: <%= event.date %></p><br />
												</div>
												<div class="modal-footer">
													<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
													<%= link_to 'Delete', future_event_path(event), :method => 'delete', :class => 'button' %>
												</div>
											</div>
										</div>
									</div>
                </div>
							</div>
            </td>
			    </tr>
				</tbody>
				<% end %>
			</table>
		</div>
		<div class="row">
			<!-- Add future event Modal button -->
			<div class="col-12">
				<button type="button" title="Add new event" class="button" data-toggle="modal" data-target="#AddfModal">
					Add new future event
				</button>
			</div>
		</div>
		<!-- Add future event Modal -->
		<div class="modal fade" id="AddfModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Add new future event</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="container text-center">
						<div class="row form-group">
							<div class="col"></div>
							<div class="col-8"><br />
								<%= form_for @future_events.new, :method => 'post' do |f| %>
									<%= render(:partial => 'feventForm', locals: {:f => f}) %>
									<%= f.submit "Add new future event", :class => 'button submit' %>
								<% end %>
							</div>
							<div class="col"></div>
						</div>
					</div>
					<div class="modal-footer">
						<%= link_to 'Cancel', admin_path, :'data-dismiss' => "modal", :class => 'button' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
	<head>
    <title>Renovacion Catolica Carismatica</title>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Description of the page less than 150 characters">
		<%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
		<script src="https://js.stripe.com/v3/"></script>
	</head>
  <body>
    <%= yield %>
		<div class="container-fluid title">
			<div class="row">
				<footer class="col">
					<p class="text-center bye"><em>Que tengas un buen dia</em></p>
					<p>©2017 my website</p>
				</footer>
			</div>
		</div>
		<%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/main/evangelizacion.html.erb
<article>
  <div class="container">
    <header class="row adminl text-right">
      <div class="col">
        <%= link_to 'Principal', root_path, :class => 'adminlink' %>
      </div>
    </header>
  </div>
  <div class="container text-center">
    <header class="row">
      <h1 class="col">Renovacion Catolica Caristmatica</h1>
    </header>
  </div>
  <div class="container-fluid text-center title">
		<div class="row">
      <div class="col circle1"></div>
		  <h2 class="col-9 col-sm-4">Evangelización</h2>
			<div class="col circle2"></div>
	  </div>
	</div>
</article>

app/views/main/formacion.html.erb
<article>
  <div class="container">
    <header class="row adminl text-right">
      <div class="col">
        <%= link_to 'Principal', root_path, :class => 'adminlink' %>
      </div>
    </header>
  </div>
  <div class="container text-center">
    <header class="row">
      <h1 class="col">Renovacion Catolica Caristmatica</h1>
    </header>
  </div>
  <div class="container-fluid text-center title">
		<div class="row">
      <div class="col circle1"></div>
		  <h2 class="col-9 col-sm-3">Formación</h2>
			<div class="col circle2"></div>
	  </div>
	</div>
  <div class="container text-center">
    <div class="row">
      <section class="col-sm-12">
        <h3>Que es la formacion?</h3>
        <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing
          elit. Mollitia nostrum voluptatibus totam voluptates autem neque aliquid nam?
          Reprehenderit, beatae. Odit ut, odio sint deleniti consectetur. Itaque odit,
          tempore deserunt eos, ipsam commodi possimus earum aliquam. Qui voluptas ad
          sit explicabo voluptatum odio impedit, dignissimos praesentium eius architecto
          suscipit, corrupti, culpa asperiores nobis voluptate. Quis distinctio suscipit,
          ea incidunt quisquam, officiis architecto corrupti aspernatur amet quia
          dignissimos, sit consectetur! Saepe nostrum aperiam sit aspernatur quaerat,
          blanditiis dolor nulla temporibus iure ut, animi culpa vitae a harum quas quod
          quis autem nesciunt consequatur et illo eum est aliquid unde. Quae, aspernatur
          repellendus, neque ipsam itaque unde repudiandae nulla? Dignissimos cumque laudantium
          nihil quos! Autem aliquid dolores animi iusto unde, eveniet ipsam, aspernatur
          dolorem reiciendis ut reprehenderit impedit sunt nihil quibusdam. Totam earum,
          ratione quod architecto, vitae voluptate sed. Rerum vero eveniet cupiditate inventore.
          Reprehenderit maiores cumque voluptatum inventore aperiam quisquam esse itaque
          vitae sed ad consequuntur eaque vero veniam fugiat officiis excepturi, aspernatur
          qui ratione ea repellat quidem enim. Est nemo, inventore laudantium praesentium
          ducimus quaerat. Aliquam asperiores, voluptatibus fugiat rerum hic facere explicabo
          recusandae neque quibusdam unde veniam voluptates, illum magni ex accusamus nulla?
          Commodi corporis sequi minima, perspiciatis, numquam animi. Vero ducimus, dolorum
          excepturi alias deleniti velit similique molestias non porro odit veritatis voluptate
          iure, sed totam quam error nesciunt a esse culpa hic minus! Modi facilis voluptatum,
          quaerat dicta quam libero eos minus omnis tenetur laudantium debitis quae amet praesentium
          saepe quia eveniet similique assumenda, quisquam mollitia inventore exercitationem!</p>
      </section>
    </div>
  </div>
</article>